version: '3.7'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ..:/usr/src/hypha/
    ports:
      - 8080:8080
    environment:
      - DJANGO_SETTINGS_MODULE=opentech.settings.dev
      - DATABASE_URL=postgres://hypha:hypha@db:5432/hypha
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hypha
      - POSTGRES_PASSWORD=hypha
      - POSTGRES_DB=hypha

volumes:
  postgres_data:
